// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using yourComplaint.Models;

namespace yourComplaint.Migrations
{
    [DbContext(typeof(ComplaintContext))]
    [Migration("20180122232700_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("yourComplaint.Models.Complaint", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company");

                    b.Property<string>("Complain");

                    b.Property<string>("Mail");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Complaint");
                });
#pragma warning restore 612, 618
        }
    }
}
