using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace yourComplaint.Models
{
    public class Complaint
    {
        //The ID will be automatically generated by the Data Base
        public int ID{get; set;}
        public string Name{get; set;}
        public string Mail{get; set;}
        public string Company{get; set;}
        public string Complain{get; set;}
    }
}